name: Release Flutter APK

on:
#   workflow_dispatch:
  workflow_run:
   workflows: ["Build Flutter APK"]
   types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact from latest successful workflow run
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml         # change to your actual build workflow file name
          name: app-release.apk
          path: extracted-apk
        #   commit: ${{ github.sha }}
          branch: main
          event: push

      - name: Get version from pubspec.yaml
        id: version
        run: |
          VERSION=$(grep 'version:' pubspec.yaml | awk '{print $2}' | tr -d "'" | tr -d '"')
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "Detected version: $VERSION"

      - name: Rename APK with version
        run: |
          cp extracted-apk/app-release.apk "socian-v${{ steps.version.outputs.VERSION }}.apk"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: socian-v${{ steps.version.outputs.VERSION }}.apk
          tag_name: v${{ steps.version.outputs.VERSION }}
          name: "v${{ steps.version.outputs.VERSION }}"
          body: |
            Automated release for version ${{ steps.version.outputs.VERSION }}
